server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: 1

scrape_configs:
  - job_name: collect-logs
    static_configs:
      labels:
        __path__: /var/log/loki/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            message: message
            shopID: shopID
      - regex:
          expression: "/var/log/loki/(?P<job>[^/]+).log"
      - labels:
          job:
          filename:
