services:
  qdrant-node-1:
    image: qdrant/qdrant:v1.15.3
    container_name: qdrant-node-1
    ports:
      - "7333:6333"
      - "7334:6334"
    environment:
      QDRANT__LOG_LEVEL: info
      QDRANT__CLUSTER__ENABLED: true
    command: "./qdrant --uri http://qdrant-node-1:6335"

  qdrant-node-2:
    image: qdrant/qdrant:v1.15.3
    container_name: qdrant-node-2
    depends_on:
      - qdrant-node-1
    ports:
      - "8333:6333"
      - "8334:6334"
    environment:
      QDRANT__LOG_LEVEL: info
      QDRANT__CLUSTER__ENABLED: true
    command: "./qdrant --bootstrap http://qdrant-node-1:6335 --uri http://qdrant-node-2:6335"

  qdrant-node-3:
    image: qdrant/qdrant:v1.15.3
    container_name: qdrant-node-3
    depends_on:
      - qdrant-node-1
    ports:
      - "9333:6333"
      - "9334:6334"
    environment:
      QDRANT__LOG_LEVEL: info
      QDRANT__CLUSTER__ENABLED: true
    command: "./qdrant --bootstrap http://qdrant-node-1:6335 --uri http://qdrant-node-3:6335"
