receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    tls:
      insecure: true
    endpoint: "tempo:4317"
    
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [spanmetrics, otlp]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      level: detailed

connectors:
  spanmetrics:
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.route
    exemplars:
      enabled: true