receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    tls:
      insecure: true
    endpoint: "tempo:4317"
    
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp]
  telemetry:
    metrics:
      address: 0.0.0.0:8888
      level: detailed